# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: aelassas.servy
PackageVersion: "1.0"
ManifestType: installer
ManifestVersion: 1.10.0

Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/aelassas/servy/releases/download/v1.0/servy-1.0-net8.0-x64-installer.exe
    InstallerSha256: 4AFD0680789126FD43FB79AA92E4AF914B443C514852AFC158CAC1C7590D2DAD
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART /SUPPRESSMSGBOXES
      SilentWithProgress: /SILENT /NORESTART /SUPPRESSMSGBOXES
    UninstallCommand: '"C:\Program Files\Servy\unins000.exe" /VERYSILENT /NORESTART'
