//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.CLI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied. Please restart your shell as Administrator to run the &apos;{0}&apos; command..
        /// </summary>
        public static string Msg_AdminPrivilegesRequired {
            get {
                return ResourceManager.GetString("Msg_AdminPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; was cancelled by the user..
        /// </summary>
        public static string Msg_CommandCancelled {
            get {
                return ResourceManager.GetString("Msg_CommandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}: {1}.
        /// </summary>
        public static string Msg_CommandFailedTemplate {
            get {
                return ResourceManager.GetString("Msg_CommandFailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file type is required (XML or JSON)..
        /// </summary>
        public static string Msg_ConfigFileTypeRequired {
            get {
                return ResourceManager.GetString("Msg_ConfigFileTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export configuration for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ExportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ExportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service exists in the database and you have write permissions to the destination path..
        /// </summary>
        public static string Msg_ExportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ExportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration exported successfully to: {1}.
        /// </summary>
        public static string Msg_ExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize the service configuration. Nothing was imported..
        /// </summary>
        public static string Msg_ImportDeserializationFailure {
            get {
                return ResourceManager.GetString("Msg_ImportDeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file is not valid: {1}.
        /// </summary>
        public static string Msg_ImportFormatInvalid {
            get {
                return ResourceManager.GetString("Msg_ImportFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service configuration was saved, but the service &apos;{0}&apos; could not be located for installation..
        /// </summary>
        public static string Msg_ImportInstallLookupFailure {
            get {
                return ResourceManager.GetString("Msg_ImportInstallLookupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration saved and service &apos;{1}&apos; installed successfully..
        /// </summary>
        public static string Msg_ImportInstallSuccess {
            get {
                return ResourceManager.GetString("Msg_ImportInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import {0} configuration into the repository..
        /// </summary>
        public static string Msg_ImportRepoFailure {
            get {
                return ResourceManager.GetString("Msg_ImportRepoFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import configuration from &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ImportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ImportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that the file path is correct, the file format is valid JSON or XML, and you have read permissions..
        /// </summary>
        public static string Msg_ImportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ImportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration imported successfully..
        /// </summary>
        public static string Msg_ImportSuccessNoInstall {
            get {
                return ResourceManager.GetString("Msg_ImportSuccessNoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_InstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_InstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the executable path is correct, the service name is not already in use, and you are running with Administrator privileges..
        /// </summary>
        public static string Msg_InstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_InstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; installed successfully..
        /// </summary>
        public static string Msg_InstallSuccess {
            get {
                return ResourceManager.GetString("Msg_InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}: &apos;{1}&apos;. Valid options: {2}.
        /// </summary>
        public static string Msg_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Msg_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid executable path: {0}. Ensure the file exists and is accessible..
        /// </summary>
        public static string Msg_InvalidExecutablePath {
            get {
                return ResourceManager.GetString("Msg_InvalidExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer format for {0}: &apos;{1}&apos;.
        /// </summary>
        public static string Msg_InvalidIntegerFormat {
            get {
                return ResourceManager.GetString("Msg_InvalidIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}.
        /// </summary>
        public static string Msg_LogFailed {
            get {
                return ResourceManager.GetString("Msg_LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0} (Unauthorized).
        /// </summary>
        public static string Msg_LogFailedUnauthorized {
            get {
                return ResourceManager.GetString("Msg_LogFailedUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is required..
        /// </summary>
        public static string Msg_PathRequired {
            get {
                return ResourceManager.GetString("Msg_PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: service operation completed successfully, but post-success repository synchronization failed for &apos;{1}&apos;: {2}.
        /// </summary>
        public static string Msg_PostSuccessSyncFailed {
            get {
                return ResourceManager.GetString("Msg_PostSuccessSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing environment....
        /// </summary>
        public static string Msg_PreparingEnvironment {
            get {
                return ResourceManager.GetString("Msg_PreparingEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_RestartServiceAction {
            get {
                return ResourceManager.GetString("Msg_RestartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is currently installed and that your account has sufficient permissions to stop and start services..
        /// </summary>
        public static string Msg_RestartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_RestartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; restarted successfully..
        /// </summary>
        public static string Msg_RestartSuccess {
            get {
                return ResourceManager.GetString("Msg_RestartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: failed to {1}: {2}.
        /// </summary>
        public static string Msg_ServiceOperationFailed {
            get {
                return ResourceManager.GetString("Msg_ServiceOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query status for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ServiceStatusAction {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Msg_ServiceStatusResult {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the service name is spelled correctly and that it is currently installed on this system..
        /// </summary>
        public static string Msg_ServiceStatusSuggestion {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show configuration for service '{0}'.
        /// </summary>
        public static string Msg_ShowServiceAction {
            get {
                return ResourceManager.GetString("Msg_ShowServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed configuration for service '{0}'..
        /// </summary>
        public static string Msg_ShowServiceLogged {
            get {
                return ResourceManager.GetString("Msg_ShowServiceLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service exists in the Servy database and that your shell is running as Administrator..
        /// </summary>
        public static string Msg_ShowServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ShowServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list services.
        /// </summary>
        public static string Msg_ShowServicesAction {
            get {
                return ResourceManager.GetString("Msg_ShowServicesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed {0} service(s)..
        /// </summary>
        public static string Msg_ShowServicesLogged {
            get {
                return ResourceManager.GetString("Msg_ShowServicesLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string Msg_Show_Column_Description {
            get {
                return ResourceManager.GetString("Msg_Show_Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY NAME.
        /// </summary>
        public static string Msg_Show_Column_DisplayName {
            get {
                return ResourceManager.GetString("Msg_Show_Column_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string Msg_Show_Column_Name {
            get {
                return ResourceManager.GetString("Msg_Show_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string Msg_Show_Column_Pid {
            get {
                return ResourceManager.GetString("Msg_Show_Column_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTUP TYPE.
        /// </summary>
        public static string Msg_Show_Column_StartupType {
            get {
                return ResourceManager.GetString("Msg_Show_Column_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string Msg_Show_Column_Status {
            get {
                return ResourceManager.GetString("Msg_Show_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Msg_Show_Disabled {
            get {
                return ResourceManager.GetString("Msg_Show_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Msg_Show_Enabled {
            get {
                return ResourceManager.GetString("Msg_Show_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Msg_Show_Group_Account {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Msg_Show_Group_Environment {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Program.
        /// </summary>
        public static string Msg_Show_Group_FailureProgram {
            get {
                return ResourceManager.GetString("Msg_Show_Group_FailureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Msg_Show_Group_Logs {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Msg_Show_Group_Other {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Launch.
        /// </summary>
        public static string Msg_Show_Group_PostLaunch {
            get {
                return ResourceManager.GetString("Msg_Show_Group_PostLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Stop.
        /// </summary>
        public static string Msg_Show_Group_PostStop {
            get {
                return ResourceManager.GetString("Msg_Show_Group_PostStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Launch.
        /// </summary>
        public static string Msg_Show_Group_PreLaunch {
            get {
                return ResourceManager.GetString("Msg_Show_Group_PreLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Stop.
        /// </summary>
        public static string Msg_Show_Group_PreStop {
            get {
                return ResourceManager.GetString("Msg_Show_Group_PreStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string Msg_Show_Group_Recovery {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeouts.
        /// </summary>
        public static string Msg_Show_Group_Timeouts {
            get {
                return ResourceManager.GetString("Msg_Show_Group_Timeouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Stderr.
        /// </summary>
        public static string Msg_Show_Label_ActiveStderr {
            get {
                return ResourceManager.GetString("Msg_Show_Label_ActiveStderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Stdout.
        /// </summary>
        public static string Msg_Show_Label_ActiveStdout {
            get {
                return ResourceManager.GetString("Msg_Show_Label_ActiveStdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console UI.
        /// </summary>
        public static string Msg_Show_Label_ConsoleUI {
            get {
                return ResourceManager.GetString("Msg_Show_Label_ConsoleUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Affinity.
        /// </summary>
        public static string Msg_Show_Label_CpuAffinity {
            get {
                return ResourceManager.GetString("Msg_Show_Label_CpuAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Rotation.
        /// </summary>
        public static string Msg_Show_Label_DateRotation {
            get {
                return ResourceManager.GetString("Msg_Show_Label_DateRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Logs.
        /// </summary>
        public static string Msg_Show_Label_DebugLogs {
            get {
                return ResourceManager.GetString("Msg_Show_Label_DebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Msg_Show_Label_Dependencies {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Msg_Show_Label_Description {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Msg_Show_Label_DisplayName {
            get {
                return ResourceManager.GetString("Msg_Show_Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        public static string Msg_Show_Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Msg_Show_Label_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string Msg_Show_Label_Executable {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string Msg_Show_Label_HealthCheck {
            get {
                return ResourceManager.GetString("Msg_Show_Label_HealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat.
        /// </summary>
        public static string Msg_Show_Label_Heartbeat {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat URL.
        /// </summary>
        public static string Msg_Show_Label_HeartbeatUrl {
            get {
                return ResourceManager.GetString("Msg_Show_Label_HeartbeatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Failure.
        /// </summary>
        public static string Msg_Show_Label_IgnoreFailure {
            get {
                return ResourceManager.GetString("Msg_Show_Label_IgnoreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time.
        /// </summary>
        public static string Msg_Show_Label_LocalTimeRotation {
            get {
                return ResourceManager.GetString("Msg_Show_Label_LocalTimeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log As Error.
        /// </summary>
        public static string Msg_Show_Label_LogAsError {
            get {
                return ResourceManager.GetString("Msg_Show_Label_LogAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Attempts.
        /// </summary>
        public static string Msg_Show_Label_MaxAttempts {
            get {
                return ResourceManager.GetString("Msg_Show_Label_MaxAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Failed Checks.
        /// </summary>
        public static string Msg_Show_Label_MaxFailedChecks {
            get {
                return ResourceManager.GetString("Msg_Show_Label_MaxFailedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Files.
        /// </summary>
        public static string Msg_Show_Label_MaxFiles {
            get {
                return ResourceManager.GetString("Msg_Show_Label_MaxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Msg_Show_Label_Name {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Clean Exit.
        /// </summary>
        public static string Msg_Show_Label_OnCleanExit {
            get {
                return ResourceManager.GetString("Msg_Show_Label_OnCleanExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Msg_Show_Label_Parameters {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pid.
        /// </summary>
        public static string Msg_Show_Label_Pid {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Msg_Show_Label_Priority {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string Msg_Show_Label_Recovery {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Attempts.
        /// </summary>
        public static string Msg_Show_Label_RetryAttempts {
            get {
                return ResourceManager.GetString("Msg_Show_Label_RetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Period.
        /// </summary>
        public static string Msg_Show_Label_RotationPeriod {
            get {
                return ResourceManager.GetString("Msg_Show_Label_RotationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Size.
        /// </summary>
        public static string Msg_Show_Label_RotationSize {
            get {
                return ResourceManager.GetString("Msg_Show_Label_RotationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local System.
        /// </summary>
        public static string Msg_Show_Label_RunAsLocalSystem {
            get {
                return ResourceManager.GetString("Msg_Show_Label_RunAsLocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Rotation.
        /// </summary>
        public static string Msg_Show_Label_SizeRotation {
            get {
                return ResourceManager.GetString("Msg_Show_Label_SizeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Msg_Show_Label_Start {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Dir.
        /// </summary>
        public static string Msg_Show_Label_StartupDir {
            get {
                return ResourceManager.GetString("Msg_Show_Label_StartupDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type.
        /// </summary>
        public static string Msg_Show_Label_StartupType {
            get {
                return ResourceManager.GetString("Msg_Show_Label_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Msg_Show_Label_Status {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stderr.
        /// </summary>
        public static string Msg_Show_Label_Stderr {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Stderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stdout.
        /// </summary>
        public static string Msg_Show_Label_Stdout {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Stdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Msg_Show_Label_Stop {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Msg_Show_Label_Timeout {
            get {
                return ResourceManager.GetString("Msg_Show_Label_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Flags.
        /// </summary>
        public static string Msg_Show_Label_UrlFlags {
            get {
                return ResourceManager.GetString("Msg_Show_Label_UrlFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Timeout.
        /// </summary>
        public static string Msg_Show_Label_UrlTimeout {
            get {
                return ResourceManager.GetString("Msg_Show_Label_UrlTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string Msg_Show_Label_UserAccount {
            get {
                return ResourceManager.GetString("Msg_Show_Label_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string Msg_Show_Megabytes {
            get {
                return ResourceManager.GetString("Msg_Show_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The --search option cannot be combined with --name. Use --name to show a single service, or --search to filter the service list..
        /// </summary>
        public static string Msg_Show_NameAndSearchNotAllowed {
            get {
                return ResourceManager.GetString("Msg_Show_NameAndSearchNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Msg_Show_No {
            get {
                return ResourceManager.GetString("Msg_Show_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services found..
        /// </summary>
        public static string Msg_Show_NoServices {
            get {
                return ResourceManager.GetString("Msg_Show_NoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        public static string Msg_Show_Seconds {
            get {
                return ResourceManager.GetString("Msg_Show_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service(s)..
        /// </summary>
        public static string Msg_Show_ServiceCount {
            get {
                return ResourceManager.GetString("Msg_Show_ServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Msg_Show_ValueNotSet {
            get {
                return ResourceManager.GetString("Msg_Show_ValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Msg_Show_Yes {
            get {
                return ResourceManager.GetString("Msg_Show_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StartServiceAction {
            get {
                return ResourceManager.GetString("Msg_StartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is installed, the executable path is valid, and the service account has &apos;Log On As Service&apos; rights..
        /// </summary>
        public static string Msg_StartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; started successfully..
        /// </summary>
        public static string Msg_StartSuccess {
            get {
                return ResourceManager.GetString("Msg_StartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StopServiceAction {
            get {
                return ResourceManager.GetString("Msg_StopServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you have Administrator privileges. If the service is unresponsive, you may need to terminate the process manually via Task Manager..
        /// </summary>
        public static string Msg_StopServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StopServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; stopped successfully..
        /// </summary>
        public static string Msg_StopSuccess {
            get {
                return ResourceManager.GetString("Msg_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion: {0}.
        /// </summary>
        public static string Msg_SuggestionTemplate {
            get {
                return ResourceManager.GetString("Msg_SuggestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstall service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_UninstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is stopped before uninstalling and that you are running this command as an Administrator..
        /// </summary>
        public static string Msg_UninstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; uninstalled successfully..
        /// </summary>
        public static string Msg_UninstallSuccess {
            get {
                return ResourceManager.GetString("Msg_UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string Msg_UnknownError {
            get {
                return ResourceManager.GetString("Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported configuration file type: {0}.
        /// </summary>
        public static string Msg_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Msg_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapper executable not found at: {0}. Ensure Servy is properly installed..
        /// </summary>
        public static string Msg_WrapperNotFound {
            get {
                return ResourceManager.GetString("Msg_WrapperNotFound", resourceCulture);
            }
        }
    }
}
