//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Manager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string Button_CollapseAll {
            get {
                return ResourceManager.GetString("Button_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        public static string Button_Config {
            get {
                return ResourceManager.GetString("Button_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy PID.
        /// </summary>
        public static string Button_CopyPid {
            get {
                return ResourceManager.GetString("Button_CopyPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string Button_ExpandAll {
            get {
                return ResourceManager.GetString("Button_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON.
        /// </summary>
        public static string Button_ExportJSON {
            get {
                return ResourceManager.GetString("Button_ExportJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML.
        /// </summary>
        public static string Button_ExportXML {
            get {
                return ResourceManager.GetString("Button_ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Actions.
        /// </summary>
        public static string Button_More {
            get {
                return ResourceManager.GetString("Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Button_Restart {
            get {
                return ResourceManager.GetString("Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Selected.
        /// </summary>
        public static string Button_RestartSelected {
            get {
                return ResourceManager.GetString("Button_RestartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Resume.
        /// </summary>
        public static string Button_Resume {
            get {
                return ResourceManager.GetString("Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Button_Searching {
            get {
                return ResourceManager.GetString("Button_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Selected.
        /// </summary>
        public static string Button_StartSelected {
            get {
                return ResourceManager.GetString("Button_StartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Selected.
        /// </summary>
        public static string Button_StopSelected {
            get {
                return ResourceManager.GetString("Button_StopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string Column_CPU {
            get {
                return ResourceManager.GetString("Column_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Column_Description {
            get {
                return ResourceManager.GetString("Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Column_Level {
            get {
                return ResourceManager.GetString("Column_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On As.
        /// </summary>
        public static string Column_LogOnAs {
            get {
                return ResourceManager.GetString("Column_LogOnAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Column_Message {
            get {
                return ResourceManager.GetString("Column_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string Column_Pid {
            get {
                return ResourceManager.GetString("Column_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string Column_RAM {
            get {
                return ResourceManager.GetString("Column_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Column_Service {
            get {
                return ResourceManager.GetString("Column_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type.
        /// </summary>
        public static string Column_StartupType {
            get {
                return ResourceManager.GetString("Column_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Column_Status {
            get {
                return ResourceManager.GetString("Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Column_Time {
            get {
                return ResourceManager.GetString("Column_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart selected services?.
        /// </summary>
        public static string Confirm_RestartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_RestartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start selected services?.
        /// </summary>
        public static string Confirm_StartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop selected services?.
        /// </summary>
        public static string Confirm_StopSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StopSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable service stdout/stderr redirection to live-monitor console output.
        /// </summary>
        public static string Console_Info {
            get {
                return ResourceManager.GetString("Console_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dependency tree (via SCM).
        /// </summary>
        public static string Dependencies_Info {
            get {
                return ResourceManager.GetString("Dependencies_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Configuration exported successfully..
        /// </summary>
        public static string ExportJson_Success {
            get {
                return ResourceManager.GetString("ExportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Configuration exported successfully..
        /// </summary>
        public static string ExportXml_Success {
            get {
                return ResourceManager.GetString("ExportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} logs in {1}.
        /// </summary>
        public static string Footer_Log_Many {
            get {
                return ResourceManager.GetString("Footer_Log_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found in {1}.
        /// </summary>
        public static string Footer_Log_None {
            get {
                return ResourceManager.GetString("Footer_Log_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 log in {1}.
        /// </summary>
        public static string Footer_Log_One {
            get {
                return ResourceManager.GetString("Footer_Log_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        public static string Footer_LogRowText {
            get {
                return ResourceManager.GetString("Footer_LogRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} services in {1}.
        /// </summary>
        public static string Footer_Service_Many {
            get {
                return ResourceManager.GetString("Footer_Service_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services loaded in {1}.
        /// </summary>
        public static string Footer_Service_None {
            get {
                return ResourceManager.GetString("Footer_Service_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded 1 service in {1}.
        /// </summary>
        public static string Footer_Service_One {
            get {
                return ResourceManager.GetString("Footer_Service_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string Footer_ServiceRowText {
            get {
                return ResourceManager.GetString("Footer_ServiceRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import JSON Configuration..
        /// </summary>
        public static string ImportJson_Error {
            get {
                return ResourceManager.GetString("ImportJson_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Configuration imported successfully..
        /// </summary>
        public static string ImportJson_Success {
            get {
                return ResourceManager.GetString("ImportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import XML Configuration..
        /// </summary>
        public static string ImportXml_Error {
            get {
                return ResourceManager.GetString("ImportXml_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Configuration imported successfully..
        /// </summary>
        public static string ImportXml_Success {
            get {
                return ResourceManager.GetString("ImportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Label_ConsoleTab {
            get {
                return ResourceManager.GetString("Label_ConsoleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Label_Copy {
            get {
                return ResourceManager.GetString("Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string Label_CPU {
            get {
                return ResourceManager.GetString("Label_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Running (green), Stopped (red), Cycle (orange).
        /// </summary>
        public static string Label_Dependencies_Gear_Info {
            get {
                return ResourceManager.GetString("Label_Dependencies_Gear_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Label_DependenciesTab {
            get {
                return ResourceManager.GetString("Label_DependenciesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service statuses auto-refresh - Press F5 to refresh the full list.
        /// </summary>
        public static string Label_F5_Shortcut {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F5 to refresh the dependency tree.
        /// </summary>
        public static string Label_F5_Shortcut_Dependencies {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F5 to refresh logs.
        /// </summary>
        public static string Label_F5_Shortcut_Logs {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching....
        /// </summary>
        public static string Label_Fetching {
            get {
                return ResourceManager.GetString("Label_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword:.
        /// </summary>
        public static string Label_Keyword {
            get {
                return ResourceManager.GetString("Label_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Label_LogsTab {
            get {
                return ResourceManager.GetString("Label_LogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Label_PerformanceTab {
            get {
                return ResourceManager.GetString("Label_PerformanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string Label_Pid {
            get {
                return ResourceManager.GetString("Label_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string Label_RAM {
            get {
                return ResourceManager.GetString("Label_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Label_ServicesTab {
            get {
                return ResourceManager.GetString("Label_ServicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Servy Manager.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurator.
        /// </summary>
        public static string Menu_Config {
            get {
                return ResourceManager.GetString("Menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / Documentation.
        /// </summary>
        public static string Menu_Doc {
            get {
                return ResourceManager.GetString("Menu_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import JSON configuration.
        /// </summary>
        public static string Menu_ImportJson {
            get {
                return ResourceManager.GetString("Menu_ImportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import XML configuration.
        /// </summary>
        public static string Menu_ImportXml {
            get {
                return ResourceManager.GetString("Menu_ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations failed..
        /// </summary>
        public static string Msg_AllOperationsFailed {
            get {
                return ResourceManager.GetString("Msg_AllOperationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Desktop App not found..
        /// </summary>
        public static string Msg_DesktopAppNotFound {
            get {
                return ResourceManager.GetString("Msg_DesktopAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load service dependency tree..
        /// </summary>
        public static string Msg_FailedToLoadDependencyTree {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadDependencyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load JSON service configuration..
        /// </summary>
        public static string Msg_FailedToLoadJson {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML service configuration..
        /// </summary>
        public static string Msg_FailedToLoadXml {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with this name already exists. Would you like to replace it?
        ///
        ///You need to click Install after importing and restart the service for changes to take effect.
        ///If the service is disabled and marked for deletion, installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ImportServiceConfirmation {
            get {
                return ResourceManager.GetString("Msg_ImportServiceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service name..
        /// </summary>
        public static string Msg_InvalidServiceName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while switching tabs. Please try again..
        /// </summary>
        public static string Msg_MainTabControl_SelectionChangedError {
            get {
                return ResourceManager.GetString("Msg_MainTabControl_SelectionChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services selected..
        /// </summary>
        public static string Msg_NoServicesSelected {
            get {
                return ResourceManager.GetString("Msg_NoServicesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string Msg_OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing the operation on: {0}.
        /// </summary>
        public static string Msg_OperationCompletedWithErrorsDetails {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedWithErrorsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID copied to clipboard..
        /// </summary>
        public static string Msg_PidCopied {
            get {
                return ResourceManager.GetString("Msg_PidCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy PID to clipboard..
        /// </summary>
        public static string Msg_PidCopyFailed {
            get {
                return ResourceManager.GetString("Msg_PidCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_RemoveServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_RemoveServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Manager requires administrative privileges to manage system services..
        /// </summary>
        public static string Msg_SecurityWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Required.
        /// </summary>
        public static string Msg_SecurityWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with this name already exists. Would you like to replace it?
        ///
        ///If the service is disabled and marked for deletion, installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Security Risk: Your system is using an outdated SQLite engine ({0}). This version of the application requires SQLite {1} or higher to mitigate CVE-2025-6965..
        /// </summary>
        public static string Msg_SqliteVersionWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert.
        /// </summary>
        public static string Msg_SqliteVersionWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_UninstallServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON configuration.
        /// </summary>
        public static string SaveFileDialog_JsonTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_JsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML configuration.
        /// </summary>
        public static string SaveFileDialog_XmlTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_XmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Servy Manager....
        /// </summary>
        public static string Splash_Text {
            get {
                return ResourceManager.GetString("Splash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string StartupType_Automatic {
            get {
                return ResourceManager.GetString("StartupType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (delayed).
        /// </summary>
        public static string StartupType_AutomaticDelayedStart {
            get {
                return ResourceManager.GetString("StartupType_AutomaticDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StartupType_Disabled {
            get {
                return ResourceManager.GetString("StartupType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string StartupType_Manual {
            get {
                return ResourceManager.GetString("StartupType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StartupType_Unknown {
            get {
                return ResourceManager.GetString("StartupType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        public static string Status_ContinuePending {
            get {
                return ResourceManager.GetString("Status_ContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string Status_NotInstalled {
            get {
                return ResourceManager.GetString("Status_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        public static string Status_PausePending {
            get {
                return ResourceManager.GetString("Status_PausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        public static string Status_StartPending {
            get {
                return ResourceManager.GetString("Status_StartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        public static string Status_StopPending {
            get {
                return ResourceManager.GetString("Status_StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Servy Manager {0}
        ///
        ///Servy Manager provides a clean and simple interface for managing Windows services created with Servy. Start, stop, configure, and monitor services with ease.
        ///
        ///Built with {1}
        ///
        ///Licensed under the MIT License.
        ///
        ///Copyright © {2} Akram El Assas. All rights reserved.
        ///    .
        /// </summary>
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_CollapseAll {
            get {
                return ResourceManager.GetString("Tooltip_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected.
        /// </summary>
        public static string Tooltip_Cycle {
            get {
                return ResourceManager.GetString("Tooltip_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_ExpandAll {
            get {
                return ResourceManager.GetString("Tooltip_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the service dependency tree.
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume live updates.
        /// </summary>
        public static string Tooltip_Resume {
            get {
                return ResourceManager.GetString("Tooltip_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is running.
        /// </summary>
        public static string Tooltip_ServiceRunning {
            get {
                return ResourceManager.GetString("Tooltip_ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is stopped.
        /// </summary>
        public static string Tooltip_ServiceStopped {
            get {
                return ResourceManager.GetString("Tooltip_ServiceStopped", resourceCulture);
            }
        }
    }
}
