//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Button_Restart {
            get {
                return ResourceManager.GetString("Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all configuration values?.
        /// </summary>
        public static string Confirm_ClearAll {
            get {
                return ResourceManager.GetString("Confirm_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily (default).
        /// </summary>
        public static string DateRotationType_Daily {
            get {
                return ResourceManager.GetString("DateRotationType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string DateRotationType_Monthly {
            get {
                return ResourceManager.GetString("DateRotationType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DateRotationType_None {
            get {
                return ResourceManager.GetString("DateRotationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string DateRotationType_Weekly {
            get {
                return ResourceManager.GetString("DateRotationType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select standard error file.
        /// </summary>
        public static string Dialog_SelectStderrFile {
            get {
                return ResourceManager.GetString("Dialog_SelectStderrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select standard output file.
        /// </summary>
        public static string Dialog_SelectStdoutFile {
            get {
                return ResourceManager.GetString("Dialog_SelectStdoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Configuration exported successfully..
        /// </summary>
        public static string ExportJson_Success {
            get {
                return ResourceManager.GetString("ExportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Configuration exported successfully..
        /// </summary>
        public static string ExportXml_Success {
            get {
                return ResourceManager.GetString("ExportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical CPUs the process may run on (e.g., &apos;0-3,8&apos; or &apos;0xFF00&apos;)..
        /// </summary>
        public static string Info_CpuAffinity {
            get {
                return ResourceManager.GetString("Info_CpuAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When both size-based and date-based rotation are enabled, size rotation takes precedence..
        /// </summary>
        public static string Info_DateRotation {
            get {
                return ResourceManager.GetString("Info_DateRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, environment variables and process parameters are recorded in the Servy.Service.log file. Not recommended for production environments, as these logs may contain sensitive information..
        /// </summary>
        public static string Info_EnableDebugLogs {
            get {
                return ResourceManager.GetString("Info_EnableDebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter variables in the format varName=varValue, one per line or separated by semicolons (;). Use \= to escape &apos;=&apos;, \&quot; to escape &apos;&quot;&apos;, \; to escape &apos;;&apos;, \\ to escape &apos;\&apos;, and %% to escape &apos;%&apos; (collapses to a single &apos;%&apos;). Supports environment variable expansion, example: VAR1=%ProgramData%\MyApp; VAR2=%VAR1%\bin.
        /// </summary>
        public static string Info_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Info_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure a script or executable to run when the process fails to start. If health monitoring is disabled, the program will run when the process fails to start. If health monitoring is enabled, the program will only run after all configured recovery action retries have failed..
        /// </summary>
        public static string Info_FailureProgram {
            get {
                return ResourceManager.GetString("Info_FailureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_FailureProgramStartupDirectory {
            get {
                return ResourceManager.GetString("Info_FailureProgramStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 for unlimited restart attempts..
        /// </summary>
        public static string Info_MaxRestartAttempts {
            get {
                return ResourceManager.GetString("Info_MaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum rotated log files to keep. Set to 0 for unlimited..
        /// </summary>
        public static string Info_MaxRotations {
            get {
                return ResourceManager.GetString("Info_MaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure an optional script or executable to run after the process starts successfully..
        /// </summary>
        public static string Info_PostLaunch {
            get {
                return ResourceManager.GetString("Info_PostLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PostLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PostLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure an optional script or executable to run after the wrapped process and all of its child processes have exited. The post-stop process is started in fire-and-forget mode and does not block service shutdown..
        /// </summary>
        public static string Info_PostStop {
            get {
                return ResourceManager.GetString("Info_PostStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PostStopStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PostStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional script to run before service start. If it fails, the service won&apos;t start unless Ignore Failure is enabled..
        /// </summary>
        public static string Info_PreLaunch {
            get {
                return ResourceManager.GetString("Info_PreLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PreLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PreLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the timeout to 0 to run in fire-and-forget mode (disables retries and logging)..
        /// </summary>
        public static string Info_PreLaunchTimeout {
            get {
                return ResourceManager.GetString("Info_PreLaunchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure an optional script or executable to run before the main service stops. Use it for graceful shutdown tasks such as notifying external systems or draining resources. The pre-stop process runs synchronously and extends the service stop timeout while running, unless the timeout is set to 0..
        /// </summary>
        public static string Info_PreStop {
            get {
                return ResourceManager.GetString("Info_PreStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If not set, defaults to the service working directory..
        /// </summary>
        public static string Info_PreStopStartupDirectory {
            get {
                return ResourceManager.GetString("Info_PreStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the timeout to 0 to run in fire-and-forget mode..
        /// </summary>
        public static string Info_PreStopTimeout {
            get {
                return ResourceManager.GetString("Info_PreStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports environment variable expansion. Example: --param=&quot;%MY_VAR%\bin&quot;.
        /// </summary>
        public static string Info_ProcessParameters {
            get {
                return ResourceManager.GetString("Info_ProcessParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports environment variable expansion, example: %JAVA_HOME%\bin\java.exe.
        /// </summary>
        public static string Info_ProcessPath {
            get {
                return ResourceManager.GetString("Info_ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart service and restart computer actions are not available if the service runs under NT AUTHORITY\NetworkService, NT AUTHORITY\LocalService, or a user account without the required privileges. Only the restart process action will be available for these accounts..
        /// </summary>
        public static string Info_RecoveryAction {
            get {
                return ResourceManager.GetString("Info_RecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run recovery action even if the process exits successfully..
        /// </summary>
        public static string Info_RecoveryOnCleanExit {
            get {
                return ResourceManager.GetString("Info_RecoveryOnCleanExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify one or more Windows service names (not display names) that this service depends on. Enter each service name on a new line or separate them with semicolons (;). Use service key names without spaces or special characters. Each dependency service must be installed and running before this service can start. If a dependency&apos;s start type is Automatic, Windows will try to start it automatically before this service. If a dependency fails to start or is disabled, this service will not start..
        /// </summary>
        public static string Info_ServiceDependencies {
            get {
                return ResourceManager.GetString("Info_ServiceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The human-readable name shown in the Windows Services console (services.msc)..
        /// </summary>
        public static string Info_ServiceDisplayName {
            get {
                return ResourceManager.GetString("Info_ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout in seconds to wait for the process to start successfully before considering the startup as failed..
        /// </summary>
        public static string Info_StartTimeout {
            get {
                return ResourceManager.GetString("Info_StartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports environment variable expansion, example: %PROGRAMDATA%\MyApp.
        /// </summary>
        public static string Info_StartupDirectory {
            get {
                return ResourceManager.GetString("Info_StartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout in seconds to wait for the process to exit..
        /// </summary>
        public static string Info_StopTimeout {
            get {
                return ResourceManager.GetString("Info_StopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service account username (e.g., .\username, DOMAIN\username, or DOMAIN\gMSA$)..
        /// </summary>
        public static string Info_UserAccount {
            get {
                return ResourceManager.GetString("Info_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the service runs under an account other than Local System, you must grant write access to %ProgramData%\Servy for the account that runs the service..
        /// </summary>
        public static string Info_UserAccountRights {
            get {
                return ResourceManager.GetString("Info_UserAccountRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Label_AdvancedTab {
            get {
                return ResourceManager.GetString("Label_AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempts.
        /// </summary>
        public static string Label_Attempts {
            get {
                return ResourceManager.GetString("Label_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpu Affinity.
        /// </summary>
        public static string Label_CpuAffinity {
            get {
                return ResourceManager.GetString("Label_CpuAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Rotation Interval.
        /// </summary>
        public static string Label_DateRotationType {
            get {
                return ResourceManager.GetString("Label_DateRotationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Console UI (for interactive console apps; disables stdout/stderr redirection).
        /// </summary>
        public static string Label_EnableConsoleUI {
            get {
                return ResourceManager.GetString("Label_EnableConsoleUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable date-based Rotation.
        /// </summary>
        public static string Label_EnableDateRotation {
            get {
                return ResourceManager.GetString("Label_EnableDateRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Debug Logs.
        /// </summary>
        public static string Label_EnableDebugLogs {
            get {
                return ResourceManager.GetString("Label_EnableDebugLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Health Monitoring.
        /// </summary>
        public static string Label_EnableHealthMonitoring {
            get {
                return ResourceManager.GetString("Label_EnableHealthMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat URL Flags (/start, /fail).
        /// </summary>
        public static string Label_EnableHeartbeatUrlFlags {
            get {
                return ResourceManager.GetString("Label_EnableHeartbeatUrlFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable size-based Rotation.
        /// </summary>
        public static string Label_EnableSizeRotation {
            get {
                return ResourceManager.GetString("Label_EnableSizeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        public static string Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Label_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat Interval.
        /// </summary>
        public static string Label_HeartbeatInterval {
            get {
                return ResourceManager.GetString("Label_HeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat URL.
        /// </summary>
        public static string Label_HeartbeatUrl {
            get {
                return ResourceManager.GetString("Label_HeartbeatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat URL Timeout.
        /// </summary>
        public static string Label_HeartbeatUrlTimeoutSeconds {
            get {
                return ResourceManager.GetString("Label_HeartbeatUrlTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Label_LoggingTab {
            get {
                return ResourceManager.GetString("Label_LoggingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string Label_LogOnTab {
            get {
                return ResourceManager.GetString("Label_LogOnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Label_MainTab {
            get {
                return ResourceManager.GetString("Label_MainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Failed Checks.
        /// </summary>
        public static string Label_MaxFailedChecks {
            get {
                return ResourceManager.GetString("Label_MaxFailedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Restart Attempts.
        /// </summary>
        public static string Label_MaxRestartAttempts {
            get {
                return ResourceManager.GetString("Label_MaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Rotations.
        /// </summary>
        public static string Label_MaxRotations {
            get {
                return ResourceManager.GetString("Label_MaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Launch.
        /// </summary>
        public static string Label_PostLaunchTab {
            get {
                return ResourceManager.GetString("Label_PostLaunchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Stop.
        /// </summary>
        public static string Label_PostStopTab {
            get {
                return ResourceManager.GetString("Label_PostStopTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Failure.
        /// </summary>
        public static string Label_PreLaunchIgnoreFailure {
            get {
                return ResourceManager.GetString("Label_PreLaunchIgnoreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Attempts.
        /// </summary>
        public static string Label_PreLaunchRetryAttempts {
            get {
                return ResourceManager.GetString("Label_PreLaunchRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Launch.
        /// </summary>
        public static string Label_PreLaunchTab {
            get {
                return ResourceManager.GetString("Label_PreLaunchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Label_PreLaunchTimeoutSeconds {
            get {
                return ResourceManager.GetString("Label_PreLaunchTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log pre-stop failure as error.
        /// </summary>
        public static string Label_PreStopLogAsError {
            get {
                return ResourceManager.GetString("Label_PreStopLogAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Stop.
        /// </summary>
        public static string Label_PreStopTab {
            get {
                return ResourceManager.GetString("Label_PreStopTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Label_PreStopTimeoutSeconds {
            get {
                return ResourceManager.GetString("Label_PreStopTimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Parameters.
        /// </summary>
        public static string Label_ProcessParameters {
            get {
                return ResourceManager.GetString("Label_ProcessParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Path *.
        /// </summary>
        public static string Label_ProcessPath {
            get {
                return ResourceManager.GetString("Label_ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Path.
        /// </summary>
        public static string Label_ProcessPathNotRequired {
            get {
                return ResourceManager.GetString("Label_ProcessPathNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Priority.
        /// </summary>
        public static string Label_ProcessPriority {
            get {
                return ResourceManager.GetString("Label_ProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Action.
        /// </summary>
        public static string Label_RecoveryAction {
            get {
                return ResourceManager.GetString("Label_RecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery even on successful exit.
        /// </summary>
        public static string Label_RecoveryOnCleanExit {
            get {
                return ResourceManager.GetString("Label_RecoveryOnCleanExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string Label_RecoveryTab {
            get {
                return ResourceManager.GetString("Label_RecoveryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required fields.
        /// </summary>
        public static string Label_RequiredFields {
            get {
                return ResourceManager.GetString("Label_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Size.
        /// </summary>
        public static string Label_RotationSize {
            get {
                return ResourceManager.GetString("Label_RotationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes (MB).
        /// </summary>
        public static string Label_RotationSizeUnit {
            get {
                return ResourceManager.GetString("Label_RotationSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Local System.
        /// </summary>
        public static string Label_RunAsLocalSystem {
            get {
                return ResourceManager.GetString("Label_RunAsLocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Label_Seconds {
            get {
                return ResourceManager.GetString("Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Dependencies.
        /// </summary>
        public static string Label_ServiceDependencies {
            get {
                return ResourceManager.GetString("Label_ServiceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description.
        /// </summary>
        public static string Label_ServiceDescription {
            get {
                return ResourceManager.GetString("Label_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Label_ServiceDisplayName {
            get {
                return ResourceManager.GetString("Label_ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name *.
        /// </summary>
        public static string Label_ServiceName {
            get {
                return ResourceManager.GetString("Label_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Timeout.
        /// </summary>
        public static string Label_StartTimeout {
            get {
                return ResourceManager.GetString("Label_StartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Directory.
        /// </summary>
        public static string Label_StartupDirectory {
            get {
                return ResourceManager.GetString("Label_StartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type.
        /// </summary>
        public static string Label_StartupType {
            get {
                return ResourceManager.GetString("Label_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stderr File Path.
        /// </summary>
        public static string Label_StderrPath {
            get {
                return ResourceManager.GetString("Label_StderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stdout File Path.
        /// </summary>
        public static string Label_StdoutPath {
            get {
                return ResourceManager.GetString("Label_StdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Timeout.
        /// </summary>
        public static string Label_StopTimeout {
            get {
                return ResourceManager.GetString("Label_StopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local time for log rotation (Default: UTC).
        /// </summary>
        public static string Label_UseLocalTimeForRotation {
            get {
                return ResourceManager.GetString("Label_UseLocalTimeForRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string Label_UserAccount {
            get {
                return ResourceManager.GetString("Label_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Servy.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Menu_ClearAll {
            get {
                return ResourceManager.GetString("Menu_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / Documentation.
        /// </summary>
        public static string Menu_Doc {
            get {
                return ResourceManager.GetString("Menu_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON configuration.
        /// </summary>
        public static string Menu_ExportJson {
            get {
                return ResourceManager.GetString("Menu_ExportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML configuration.
        /// </summary>
        public static string Menu_ExportXml {
            get {
                return ResourceManager.GetString("Menu_ExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import JSON configuration.
        /// </summary>
        public static string Menu_ImportJson {
            get {
                return ResourceManager.GetString("Menu_ImportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import XML configuration.
        /// </summary>
        public static string Menu_ImportXml {
            get {
                return ResourceManager.GetString("Menu_ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Menu_Manager {
            get {
                return ResourceManager.GetString("Menu_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required..
        /// </summary>
        public static string Msg_AdminRightsRequired {
            get {
                return ResourceManager.GetString("Msg_AdminRightsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load JSON service configuration..
        /// </summary>
        public static string Msg_FailedToLoadJson {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML service configuration..
        /// </summary>
        public static string Msg_FailedToLoadXml {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the Manager application..
        /// </summary>
        public static string Msg_ManagerAppLaunchFailed {
            get {
                return ResourceManager.GetString("Msg_ManagerAppLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Manager App not found..
        /// </summary>
        public static string Msg_ManagerAppNotFound {
            get {
                return ResourceManager.GetString("Msg_ManagerAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        public static string Msg_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy requires administrative privileges to manage system services..
        /// </summary>
        public static string Msg_SecurityWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Required.
        /// </summary>
        public static string Msg_SecurityWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with this name already exists. Would you like to replace it?
        ///
        ///If the service is disabled and marked for deletion, the installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service was not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was removed successfully..
        /// </summary>
        public static string Msg_ServiceRemoved {
            get {
                return ResourceManager.GetString("Msg_ServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Security Risk: Your system is using an outdated SQLite engine ({0}). This version of the application requires SQLite {1} or higher to mitigate CVE-2025-6965..
        /// </summary>
        public static string Msg_SqliteVersionWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert.
        /// </summary>
        public static string Msg_SqliteVersionWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        public static string ProcessPriority_AboveNormal {
            get {
                return ResourceManager.GetString("ProcessPriority_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        public static string ProcessPriority_BelowNormal {
            get {
                return ResourceManager.GetString("ProcessPriority_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string ProcessPriority_High {
            get {
                return ResourceManager.GetString("ProcessPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string ProcessPriority_Idle {
            get {
                return ResourceManager.GetString("ProcessPriority_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal (default).
        /// </summary>
        public static string ProcessPriority_Normal {
            get {
                return ResourceManager.GetString("ProcessPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time (use with caution).
        /// </summary>
        public static string ProcessPriority_RealTime {
            get {
                return ResourceManager.GetString("ProcessPriority_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RecoveryAction_None {
            get {
                return ResourceManager.GetString("RecoveryAction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Computer.
        /// </summary>
        public static string RecoveryAction_RestartComputer {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Process.
        /// </summary>
        public static string RecoveryAction_RestartProcess {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Service (default).
        /// </summary>
        public static string RecoveryAction_RestartService {
            get {
                return ResourceManager.GetString("RecoveryAction_RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON configuration.
        /// </summary>
        public static string SaveFileDialog_JsonTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_JsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML configuration.
        /// </summary>
        public static string SaveFileDialog_XmlTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_XmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Servy....
        /// </summary>
        public static string Splash_Text {
            get {
                return ResourceManager.GetString("Splash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (default).
        /// </summary>
        public static string StartupType_Automatic {
            get {
                return ResourceManager.GetString("StartupType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (delayed start).
        /// </summary>
        public static string StartupType_AutomaticDelayedStart {
            get {
                return ResourceManager.GetString("StartupType_AutomaticDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StartupType_Disabled {
            get {
                return ResourceManager.GetString("StartupType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string StartupType_Manual {
            get {
                return ResourceManager.GetString("StartupType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Servy {0}
        ///
        ///Servy lets you run any application as a native Windows service, with full control over its working directory, startup behavior, logging, health checks, and recovery options.
        ///
        ///It includes a desktop app, a CLI, and a PowerShell module, letting you manage services manually or automate everything in scripts and CI/CD pipelines.
        ///
        ///Built with {1}
        ///
        ///Licensed under the MIT License.
        ///
        ///Copyright © {2} Akram El Assas. All rights reserved.
        ///    .
        /// </summary>
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
    }
}
