# This worflow is disabled because reflection-based SCM registration has been replaced by native P/Invoke calls.

name: dotnet-reflection

on: 
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest # Required for ServiceBase reflection

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Check .NET version
        run: dotnet --version

      - name: Restore Dependencies
        run: dotnet restore Servy.sln

      - name: Build Solution
        run: dotnet build Servy.sln --configuration Debug --no-restore

      - name: Verify Reflection Compatibility (xUnit)
        shell: pwsh
        run: |
          dotnet test tests/Servy.Service.UnitTests/Servy.Service.UnitTests.csproj `
            --configuration Debug `
            --no-build `
            --filter "Category=ReflectionValidation" `
            --logger "console;verbosity=detailed"
