# ==============================================================
#  Release Workflow
# --------------------------------------------------------------
#  Purpose:
#    This workflow provides a unified "release" badge
#    that reflects the combined status of the following workflows:
#      - winget.yml       → Publishes the WinGet manifest
#      - choco.yml        → Publishes the Chocolatey package
#      - scoop.yml        → Publishes the Scoop manifest to aelassas/scoop-bucket
#      - bump-version.yml → Bumps version
#
#  Behavior:
#    • Automatically runs after any of the above workflows complete.
#    • Checks their latest runs.
#    • Fails if any of them failed, were skipped, or did not run.
#    • Can also be triggered manually from the GitHub Actions tab.
#
#  Badge:
#    ![release](https://github.com/aelassas/servy/actions/workflows/release.yml/badge.svg)
#
#  Result:
#    Green  → All release workflows succeeded
#    Red    → One or more failed or skipped
# ==============================================================

name: release

on:
  workflow_run:
    workflows: ["winget", "choco", "scoop", "bump-version"]
    types: [completed]
  workflow_dispatch:  # Manual trigger

jobs:
  check-release-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check release workflows status
        uses: actions/github-script@v7
        with:
          script: |
            const workflows = ["winget", "choco", "scoop", "bump-version"];
            let failed = [];

            for (const wf of workflows) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: `${wf}.yml`,
                per_page: 1,
              });
              
              const run = runs.data.workflow_runs[0];
              if (!run) {
                failed.push(`${wf} (not run)`);
                continue;
              }

              console.log(`${wf}: ${run.conclusion}`);
              if (run.conclusion !== "success") {
                failed.push(wf);
              }
            }

            if (failed.length > 0) {
              core.setFailed(`Some workflows failed or skipped: ${failed.join(", ")}`);
            } else {
              console.log("All release workflows succeeded!");
            }
