name: winget

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish Servy to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: aelassas.Servy
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: "servy-\\d+\\.\\d+(-net([0-9]+)(\\.[0-9]+)+)?-x64-installer\\.exe$"
